---
- import_playbook: /etc/ansible/playbook/common.yml
  when: ansible_role == "common"

- import_playbook: /etc/ansible/playbook/frontend.yml
  when: ansible_role == "frontend"

- import_playbook: /etc/ansible/playbook/backend.yml
  when: ansible_role == "backend"
