---
# tasks file for roles/backend

- name: Install apache2
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apache2

- name: Create folder /tmp/befiles 
  file:
    path: /tmp/befiles
    state: directory

# - name: Download/get s3 bucket file to the created folder
#   amazon.aws.aws_s3:
#     bucket: skillup-s3-bucket-mbragais-001
#     mode: get
#     object: "{{ s3_object }}"
#     dest: "{{ dest }}/{{ s3_object }}"
#   register: getresult

# - debug: msg="{{getresult.msg}}"
#   when: getresult.changed

- name: Copy S3 bucket file to the created folder
  command: aws s3 cp s3://skillup-s3-bucket-mbragais-001/backend.zip /tmp/befiles

- name: Clean /var/www/html directory
  file:
    path: /var/www/html/
    state: absent

- name: Create /var/www/html directory
  file:
    path: /var/www/html/
    state: directory

- name: Unzip the downloaded backend.zip file
  unarchive:
    src: /tmp/befiles/backend.zip
    dest: /var/www/html

- name: Copy html file to /var/www/html
  command: sudo cp /var/www/html/backend/index.html /var/www/html/index.html

- name: Change permission
  command: sudo chmod 666 /var/www/html/index.html

- name: Input IP address
  shell: sudo ec2metadata --local-hostname  >> /var/www/html/index.html

- name: Start apache service
  service:
    name: apache2
    state: started
    enabled: yes
